### ISSUE TITLE
Example code snippet

### ISSUE THREAD

**Issue by gam-ragnar** [lc3t35/orion-filesystem-local#1]
How to use? Give some details in the readme.

**Comment by lc3t35** [comment]
I've just corrected a typo -> there is nothing to do for this first version except meteor add as it is a provider.

**Comment by gam-ragnar** [comment]
Ok cool I will test again.

**Comment by lc3t35** [comment]
@timfam Can I close this issue ?

**Comment by gam-ragnar** [comment]
yes

**Comment by lc3t35** [comment]
thx
