### ISSUE TITLE
Dependency issue

### ISSUE THREAD

**Issue by benjick** [lc3t35/orion-filesystem-local#5]
```
=> Errors prevented startup:

   While selecting package versions:
   error: unknown package in top-level dependencies: lc3t35:orion-filesystem-local
```

**Comment by lc3t35** [comment]
the package is not yet on atmosphere (this will be done a little later), you must create a local "packages" directory and clone lc3t35:orion-filesystem-local in it. Then meteor will find it locally at startup.

**Comment by benjick** [comment]
Thanks @lc3t35!

**Comment by ondrejrohon** [comment]
Hey guys, any reason for not uploading this package to atmosphere? It'll be helpful to add some info about this to readme. Thanks.
